### ISSUE TITLE
admin email is always appserver org's?

### ISSUE THREAD

**Issue by smolinari** [appserver-io/routlt-project#12]
Hi,

working on the appserver (php) CLI, I'd like to use this repo as the skeleton for a routlt project too, however I noticed the admin email is always set as appserver's and not the user's. 

Example:

https://github.com/appserver-io/routlt-project/blob/master/templates/default/static/META-INF/containers.xml

`<param name="admin" type="string">info@appserver.io</param>`

Is this correct? 

Why I am asking this? Because, in the project creation process, the CLI will ask for the developer's name and email address, similar to how composer asks for the author's name and email address. The email address can then also be used to insert properly in the settings. 

What do you think?

If I knew my way around Ant, I'd suggest a PR. :blush: 

Scott

**Comment by wagnert** [comment]
Hi, you're right, the e-mail address should not be hardcoded. So it would be nice, if someone can specifiy when creating a new project stub using the appserver-cli :)

**Comment by smolinari** [comment]
:smile: 

Ok. I'll make sure it works in the CLI. But, can you also change it here also? I am going to use this repo for the CLI too. 

I've finished the project creation (new) command for a bare-bones project. Now I am working on creating the routlt and example projects (new --with). I haven't committed the changes yet, but if you want to follow the progress, I've noted my goals for the CLI commands here: https://github.com/skooppaos/appserver-io-cli/issues/1

Let me know what you think in the issue, or if you have any improvements. 

Scott

**Comment by wagnert** [comment]
I've updated the `appserver-io/routlt-project` library with the ability to specify an admin e-mail when creating a new project :)
